# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]

  #README commits DO NOT trigger the pipeline
  #  paths-ignore:
  #    - 'README.md'

  #pull_request:
  #  branches: [ "main" ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #Adding env. varibales globally to retrieve Secrets from Github, and set image name
    env:
      CORTEX_URL: ${{ secrets.CORTEX_URL }}
      API_ID: ${{ secrets.API_ID }}
      API_KEY: ${{ secrets.API_KEY }}
      IMAGE_NAME: "ubuntu:18.04"


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME . # Build the image, tagging it 'ubuntu:18.04'

      - name: Download Cortex dependencies
        run: |
          sudo apt install libhyperscan5
          sudo apt-get install jq

      - name: Cortex CLI install
        run: |
          crtx_resp=$(curl -s "$CORTEX_URL/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
            -H "x-xdr-auth-id: $API_ID" \
            -H "Authorization: $API_KEY") 
            
          # Check if the curl command was successful before proceeding
          if [ $? -ne 0 ] || echo "$crtx_resp" | jq -e '.error_code' > /dev/null; then
            echo "Failed to retrieve CLI download link. Response: $crtx_resp"
            exit 1
          fi

          # Parse the response using jq
          crtx_url=$(echo $crtx_resp | jq -r ".signed_url")
          crtx_file=$(echo $crtx_resp | jq -r ".file_name")
          
          # Download the file using the signed URL
          echo "Downloading $crtx_file from signed URL..."
          curl -o $crtx_file $crtx_url
          
          # Make the downloaded file executable
          chmod +x $crtx_file

      - name: Cortex CLI image scan
        run: |
          #sudo ./cortexcli  --api-base-url $CORTEX_URL --api-key $API_KEY --api-key-id $API_ID image scan $IMAGE_NAME
          sudo ./cortexcli  --api-base-url $CORTEX_URL --api-key $API_KEY --api-key-id $API_ID --soft-fail image scan $IMAGE_NAME

      - name: Cortex CLI SBOM creation
        run: |
          sudo ./cortexcli  --api-base-url $CORTEX_URL --api-key $API_KEY --api-key-id $API_ID image sbom --output-file /tmp/"$IMAGE_NAME-sbom.json" $IMAGE_NAME
          ls -la

      - name: Archive Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: image-scan-report
          path: /tmp/$IMAGE_NAME-sbom.json
          retention-days: 10             # 90 is the default
